name: build-and-verify

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # ✅ Cache dependency & target build
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Build
        run: cargo build --workspace --all-features

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings

      - name: Tests
        run: cargo test --workspace --all-features

      - name: Generate proof (release)
        run: cargo run --manifest-path supernova-gen/Cargo.toml --release

      - name: Verify proof (fresh artifacts)
        run: cargo run -- supernova-gen/proof.json supernova-gen/vk.json supernova-gen/inputs.json
